### ISSUE TITLE
Add sound effect component

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/vr-markup#14]
Enables user to add sounds to their scene.

User can specify:

* Source URL
* Position of sound
* Bounding box and falloff (not sure how to articulate this in values...)
* Loop / play-once
* User triggered (true/false. If true, sound is played when user enters bounding box)

**Comment by nickdesaulniers** [comment]
@dmarcos since the THREE.js audioListener [needs to be added to a camera](https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/examples/misc_sound.html#L74-L75), should I just do a depth first traversal from the vr-scene node until I find the first vr-camera?  Can more than one camera be specified in a scene? If so, which to I bind to? What if there's no camera in the scene?

**Comment by dmarcos** [comment]
Right now only one camera is allowed. 
You have a handle to the camera in your vr-object. this.sceneEl.camera. You could also find the element with document.querySelector('vr-camera')
If there's no user defined camera there's one added by default

**Comment by jcarpenter** [comment]
Nick checked in vr-audio today. Closing issue and we can file new issues for follow ups.
